#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 01 22:13:07 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Mellow Shader v3.2.zip
