name = "elbow modpack"
author = "ajogar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d74ee6ca8da3e288a6355433922b5955ab3925a3a1ff25dd4faca0fdcdabdba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
