name = "elbow pack"
author = "ajogar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aaa6b2d93531c3f8f027aa9f75a2aeb6134c169fd099c0a5b53c494c800273e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
