name = "GarPackUltra"
author = "ajogar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeaa24d79216250b89fcf5d6e223fd78bff5d8f9717da1c4f4d9a31984d9b80a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
