name = "GarPack Ultra test"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f16239b3e33b01e4e6b00f251563cee2edcb9991b00968fc4852f1b41f1ad774"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
