name = "GarPack Ultra FPS Edition"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a387f3db2dcf88db943673bd97cc6ed965573c6e4e1f9db1b9e06b3bcd0c84f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
